Add mutex_m require for Ruby 3.4 compatibility
In addition to the logger fix, Ruby 3.4 also requires mutex_m to be
explicitly required as it was moved from default gems.

This fixes the additional error:
LoadError: cannot load such file -- mutex_m